application: dedicationsupercoach
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "7d"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /team.*
  script: scripts.team.app

- url: /players.*
  script: scripts.players.app
  
- url: /games.*
  script: scripts.games.app
  
- url: /admin.*
  script: scripts.admin.app
  
- url: /static
  static_dir: static
  
- url: /worker.*
  static_dir: scripts.worker.app
  login: admin
  
- url: /.*
  script: scripts.main.app

libraries:
- name: webapp2
  version: latest
 
- name: jinja2
  version: latest
